version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - INSIDE_DOCKER=1
      - BASE_URL=http://web:8000

  test:
    build: .
    environment:
      - INSIDE_DOCKER=1
      - BASE_URL=http://web:8000
    depends_on:
      - web
    volumes:
      - ./tests:/app/tests
    command: pytest tests/
